version: '3.8'

services:
  rrr-model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./rrr_model:/app/rrr_model
    environment:
      - MODEL_PATH=/app/rrr_model
      - PORT=8000
      - MAX_MODEL_LEN=2048
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 